# Generated by Django 4.0 on 2022-07-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_table',
            name='location_holder',
        ),
    ]
