# Generated by Django 4.0 on 2022-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='rating_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product_table',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
