# Generated by Django 4.0 on 2022-07-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_product_table_rating_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
