# Generated by Django 4.0.5 on 2022-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_group',
            name='category_group_name',
            field=models.CharField(choices=[('Mobiles & Tablets', 'Mobiles & Tablets'), ('Computers & laptops', 'Computers & laptops'), ('Cameras', 'Cameras'), ('Television', 'Television'), ('Computer Peripherals', 'Computer Peripherals'), ('Audio', 'Audio')], max_length=30),
        ),
    ]
