# Generated by Django 4.0.5 on 2022-07-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_product_table_brand_product_table_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
