# Generated by Django 4.0.5 on 2022-07-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_app', '0006_alter_category_group_category_group_name'),
        ('user_app', '0003_custom_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.custom_user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product_table')),
            ],
        ),
    ]
