# Generated by Django 4.0.5 on 2022-07-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist_table',
        ),
    ]
