# Generated by Django 4.0 on 2022-07-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='id_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
